name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ec2-user/agno-agent/BusinessCardScanner_Backend

            git pull origin main

            source venv/bin/activate

            pip install -r requirements.txt

            sudo systemctl restart business-card

            sudo systemctl status business-card --no-pager